"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, useCallback, useEffect, useRef, useState } from "react";
import { AdminApiError, AdminOrderDetail, cancelAdminOrder, confirmAdminOrder, formatMoney, getAdminOrder, rescheduleAdminOrder } from "@/lib/admin-orders";
import { CollectorAssignmentPanel } from "@/components/collector-assignment";
type Action = "confirm" | "cancel" | "reschedule";
const slots = ["07:00-09:00", "09:00-11:00", "13:00-15:00", "15:00-17:00"];
export function AdminOrderDetailView({ orderCode }: { orderCode: string }) {
  const router = useRouter(), [order, setOrder] = useState<AdminOrderDetail | null>(null), [loading, setLoading] = useState(true), [error, setError] = useState(""), [notice, setNotice] = useState(""), [action, setAction] = useState<Action | null>(null), [saving, setSaving] = useState(false);
  const load = useCallback(async () => { setLoading(true); setError(""); try { setOrder(await getAdminOrder(orderCode)); } catch (reason) { if (reason instanceof AdminApiError && reason.status === 401) router.replace("/admin/login"); else setError(reason instanceof Error ? reason.message : "Không thể tải đơn hàng."); } finally { setLoading(false); } }, [orderCode, router]);
  useEffect(() => {
    // The detail is intentionally refreshed when its route key changes.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    void load();
  }, [load]);
  const mutate = async (operation: () => Promise<AdminOrderDetail>, message: string) => { if (saving) return; setSaving(true); setError(""); try { setOrder(await operation()); setNotice(message); setAction(null); router.refresh(); } catch (reason) { const apiError = reason instanceof AdminApiError ? reason : null; setError(apiError?.message ?? "Không thể cập nhật đơn hàng."); if (apiError?.status === 409) await load(); } finally { setSaving(false); } };
  if (loading && !order) return <p className="rounded-xl bg-white p-6">Đang tải chi tiết đơn hàng…</p>;
  if (error && !order) return <p role="alert" className="rounded-xl bg-red-50 p-6 text-red-800">{error}</p>;
  if (!order) return null;
  return <>
    <CollectorAssignmentPanel order={order} onUpdated={(updated) => { setOrder(updated); setNotice("Đã cập nhật phân công nhân viên."); }} onError={setError} />
    <div className="flex flex-wrap items-center justify-between gap-4"><div><Link className="text-teal-700 underline" href="/admin/orders">← Quay lại danh sách</Link><h1 className="mt-2 text-3xl font-bold">{order.orderCode}</h1><p className="mt-1 font-semibold">{order.statusLabel}</p></div><div className="flex flex-wrap gap-2">{order.status === "PENDING_CONFIRMATION" && <button onClick={() => setAction("confirm")} className="rounded-lg bg-teal-700 px-4 py-2 text-white">Xác nhận đơn</button>}{order.status !== "CANCELLED" && <><button onClick={() => setAction("reschedule")} className="rounded-lg border px-4 py-2">Điều chỉnh lịch</button><button onClick={() => setAction("cancel")} className="rounded-lg bg-red-700 px-4 py-2 text-white">Hủy đơn</button></>}</div></div>
    <div aria-live="polite">{notice && <p className="mt-4 rounded-lg bg-green-50 p-3 text-green-800">{notice}</p>}{error && <p role="alert" className="mt-4 rounded-lg bg-red-50 p-3 text-red-800">{error}</p>}</div>
    <div className="mt-6 grid gap-5 lg:grid-cols-2"><Section title="Thông tin liên hệ"><p>{order.contact.name}</p><p>{order.contact.phone}</p></Section><Section title="Lịch lấy mẫu"><p>{date(order.appointment.scheduledDate)} · {order.appointment.timeSlot}</p><p>{order.appointment.addressLine}, {order.appointment.ward}, {order.appointment.district}, {order.appointment.province}</p>{order.appointment.note && <p className="mt-2 text-slate-600">Ghi chú: {order.appointment.note}</p>}</Section><Section title="Danh sách xét nghiệm"><ul className="divide-y">{order.items.map((item) => <li key={item.testCode} className="flex justify-between gap-4 py-3"><span><strong>{item.testName}</strong><br/><small>{item.testCode} · {item.specimenType}</small></span><span>{formatMoney(item.price)}</span></li>)}</ul></Section><Section title="Tổng tiền"><p className="flex justify-between"><span>Tạm tính</span><span>{formatMoney(order.subtotal)}</span></p><p className="flex justify-between"><span>Phí lấy mẫu</span><span>{formatMoney(order.collectionFee)}</span></p><p className="mt-2 flex justify-between border-t pt-2 text-lg font-bold"><span>Tổng cộng</span><span>{formatMoney(order.totalAmount)}</span></p></Section></div>
    <Section title="Lịch sử"><ol className="space-y-4">{order.timeline.map((event, index) => <li key={`${event.occurredAt}-${index}`} className="border-l-4 border-teal-600 pl-4"><strong>{event.title}</strong><p>{event.description}</p><time className="text-sm text-slate-600">{date(event.occurredAt)}</time></li>)}</ol></Section>
    {action && <ActionDialog action={action} order={order} saving={saving} onClose={() => setAction(null)} onConfirm={() => void mutate(() => confirmAdminOrder(order.orderCode, order.version), "Đã xác nhận đơn hàng.")} onCancel={(reason) => void mutate(() => cancelAdminOrder(order.orderCode, order.version, reason), "Đã hủy đơn hàng.")} onReschedule={(input) => void mutate(() => rescheduleAdminOrder(order.orderCode, { ...input, expectedVersion: order.version }), "Đã cập nhật lịch lấy mẫu.")} />}
  </>;
}
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section className="mt-5 rounded-2xl bg-white p-6 shadow-sm"><h2 className="mb-4 text-xl font-bold">{title}</h2>{children}</section>; }
function ActionDialog({ action, order, saving, onClose, onConfirm, onCancel, onReschedule }: { action: Action; order: AdminOrderDetail; saving: boolean; onClose: () => void; onConfirm: () => void; onCancel: (reason: string) => void; onReschedule: (input: { scheduledDate: string; timeSlot: string; reason: string }) => void }) {
  const first = useRef<HTMLButtonElement>(null), previous = useRef<HTMLElement | null>(null), [reason, setReason] = useState(""), [scheduledDate, setScheduledDate] = useState(toLocal(order.appointment.scheduledDate)), [timeSlot, setTimeSlot] = useState(order.appointment.timeSlot), [validation, setValidation] = useState("");
  useEffect(() => { previous.current = document.activeElement as HTMLElement; first.current?.focus(); const key = (e: KeyboardEvent) => { if (e.key === "Escape" && !saving) onClose(); if (e.key === "Tab") { const dialog = document.querySelector<HTMLElement>('[role="dialog"]'); const focusable = dialog ? Array.from(dialog.querySelectorAll<HTMLElement>('button:not([disabled]), input:not([disabled]), textarea:not([disabled]), select:not([disabled]), a[href]')) : []; const firstItem = focusable[0], lastItem = focusable.at(-1); if (firstItem && lastItem && e.shiftKey && document.activeElement === firstItem) { e.preventDefault(); lastItem.focus(); } else if (firstItem && lastItem && !e.shiftKey && document.activeElement === lastItem) { e.preventDefault(); firstItem.focus(); } } }; document.addEventListener("keydown", key); return () => { document.removeEventListener("keydown", key); previous.current?.focus(); }; }, [onClose, saving]);
  const submit = (event: FormEvent) => { event.preventDefault(); if (action === "confirm") return onConfirm(); const clean = reason.trim(); if (clean.length < 3) return setValidation("Lý do phải có ít nhất 3 ký tự."); if (action === "cancel") return onCancel(clean); const chosen = new Date(scheduledDate); if (chosen.getTime() <= Date.now()) return setValidation("Lịch mới không được nằm trong quá khứ."); if (chosen.getTime() === new Date(order.appointment.scheduledDate).getTime() && timeSlot === order.appointment.timeSlot) return setValidation("Lịch mới phải khác lịch hiện tại."); onReschedule({ scheduledDate: chosen.toISOString(), timeSlot, reason: clean }); };
  // The minimum date intentionally reflects the instant the modal renders.
  // eslint-disable-next-line react-hooks/purity
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4" role="presentation"><div role="dialog" aria-modal="true" aria-labelledby="action-title" className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-xl"><h2 id="action-title" className="text-xl font-bold">{action === "confirm" ? "Xác nhận đơn hàng" : action === "cancel" ? "Hủy đơn hàng" : "Điều chỉnh lịch lấy mẫu"}</h2><p className="mt-2">Mã đơn: {order.orderCode}</p><form onSubmit={submit} className="mt-4 space-y-4">{action === "reschedule" && <><label className="block font-medium">Ngày giờ<input type="datetime-local" required min={toLocal(new Date(Date.now()+60000).toISOString())} value={scheduledDate} onChange={(e) => setScheduledDate(e.target.value)} className="mt-1 w-full rounded-lg border p-2" /></label><label className="block font-medium">Khung giờ<select value={timeSlot} onChange={(e) => setTimeSlot(e.target.value)} className="mt-1 w-full rounded-lg border p-2">{slots.map((slot) => <option key={slot}>{slot}</option>)}</select></label></>}{action !== "confirm" && <label className="block font-medium">Lý do<textarea maxLength={500} required value={reason} onChange={(e) => setReason(e.target.value)} aria-describedby="reason-help" className="mt-1 min-h-24 w-full rounded-lg border p-2" /><span id="reason-help" className="text-sm text-slate-600">{reason.length}/500 ký tự</span></label>}{validation && <p role="alert" className="text-red-700">{validation}</p>}<div className="flex justify-end gap-2"><button ref={first} type="button" disabled={saving} onClick={onClose} className="rounded-lg border px-4 py-2 disabled:opacity-50">Đóng</button><button type="submit" disabled={saving} className={`rounded-lg px-4 py-2 text-white disabled:opacity-50 ${action === "cancel" ? "bg-red-700" : "bg-teal-700"}`}>{saving ? "Đang xử lý…" : action === "confirm" ? "Xác nhận" : action === "cancel" ? "Xác nhận hủy" : "Cập nhật lịch"}</button></div></form></div></div>;
}
const date = (value: string) => new Intl.DateTimeFormat("vi-VN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value));
const toLocal = (value: string) => { const dateValue = new Date(value); const local = new Date(dateValue.getTime() - dateValue.getTimezoneOffset() * 60_000); return local.toISOString().slice(0,16); };
