"use client";
import Link from "next/link";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { useEffect, useState } from "react";
import { AdminApiError, AdminOrderList, formatMoney, getAdminOrders } from "@/lib/admin-orders";

export function AdminOrderListView() {
  const router = useRouter(), pathname = usePathname(), searchParams = useSearchParams();
  const [result, setResult] = useState<AdminOrderList | null>(null), [loading, setLoading] = useState(true), [error, setError] = useState("");
  const [search, setSearch] = useState(searchParams.get("search") ?? ""), [refreshNonce, setRefreshNonce] = useState(0);
  const query = searchParams.toString();
  useEffect(() => { let active = true;
    // Fetch state is intentionally reset when the URL query changes.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setLoading(true); setError(""); getAdminOrders(query).then((value) => active && setResult(value)).catch((reason: unknown) => { if (!active) return; if (reason instanceof AdminApiError && reason.status === 401) router.replace("/admin/login"); else setError(reason instanceof Error ? reason.message : "Không thể tải đơn hàng."); }).finally(() => active && setLoading(false)); return () => { active = false; }; }, [query, router, refreshNonce]);
  useEffect(() => { const timer = window.setTimeout(() => { const params = new URLSearchParams(searchParams.toString()); if (search.trim()) params.set("search", search.trim()); else params.delete("search"); params.delete("page"); if (params.toString() !== searchParams.toString()) router.replace(`${pathname}?${params}`); }, 400); return () => window.clearTimeout(timer); }, [search, pathname, router, searchParams]);
  const setParam = (name: string, value: string) => { const params = new URLSearchParams(searchParams.toString()); if (value) params.set(name, value); else params.delete(name); if (name !== "page") params.delete("page"); router.replace(`${pathname}?${params}`); };
  return <>
    <div className="mt-6 grid gap-3 rounded-2xl bg-white p-4 shadow-sm md:grid-cols-4">
      <label className="text-sm font-medium">Tìm kiếm<input aria-label="Tìm kiếm đơn hàng" value={search} onChange={(e) => setSearch(e.target.value)} className="mt-1 w-full rounded-lg border p-2 focus:ring-2 focus:ring-teal-600" placeholder="Mã đơn, tên hoặc điện thoại" /></label>
      <label className="text-sm font-medium">Trạng thái<select value={searchParams.get("status") ?? ""} onChange={(e) => setParam("status", e.target.value)} className="mt-1 w-full rounded-lg border p-2"><option value="">Tất cả</option><option value="PENDING_CONFIRMATION">Chờ xác nhận</option><option value="CONFIRMED">Đã xác nhận</option><option value="CANCELLED">Đã hủy</option></select></label>
      <label className="text-sm font-medium">Lịch từ<input type="date" value={searchParams.get("appointmentDateFrom")?.slice(0,10) ?? ""} onChange={(e) => setParam("appointmentDateFrom", e.target.value ? `${e.target.value}T00:00:00+07:00` : "")} className="mt-1 w-full rounded-lg border p-2" /></label>
      <label className="text-sm font-medium">Lịch đến<input type="date" value={searchParams.get("appointmentDateTo")?.slice(0,10) ?? ""} onChange={(e) => setParam("appointmentDateTo", e.target.value ? `${e.target.value}T23:59:59+07:00` : "")} className="mt-1 w-full rounded-lg border p-2" /></label>
      <label className="text-sm font-medium">Tạo từ<input type="date" value={searchParams.get("createdFrom")?.slice(0,10) ?? ""} onChange={(e) => setParam("createdFrom", e.target.value ? `${e.target.value}T00:00:00+07:00` : "")} className="mt-1 w-full rounded-lg border p-2" /></label>
      <label className="text-sm font-medium">Tạo đến<input type="date" value={searchParams.get("createdTo")?.slice(0,10) ?? ""} onChange={(e) => setParam("createdTo", e.target.value ? `${e.target.value}T23:59:59+07:00` : "")} className="mt-1 w-full rounded-lg border p-2" /></label>
      <label className="text-sm font-medium">Sắp xếp<select value={searchParams.get("sortBy") ?? "createdAt"} onChange={(e) => setParam("sortBy", e.target.value)} className="mt-1 w-full rounded-lg border p-2"><option value="createdAt">Ngày tạo</option><option value="scheduledDate">Ngày lấy mẫu</option><option value="totalAmount">Tổng tiền</option></select></label>
      <label className="text-sm font-medium">Thứ tự<select value={searchParams.get("sortOrder") ?? "desc"} onChange={(e) => setParam("sortOrder", e.target.value)} className="mt-1 w-full rounded-lg border p-2"><option value="desc">Mới nhất / giảm dần</option><option value="asc">Cũ nhất / tăng dần</option></select></label>
      <div className="flex gap-2 md:col-span-4"><button onClick={() => { setSearch(""); router.replace(pathname); }} className="rounded-lg border px-4 py-2">Đặt lại</button><button onClick={() => setRefreshNonce((value) => value + 1)} className="rounded-lg bg-teal-700 px-4 py-2 text-white">Làm mới</button></div>
    </div>
    <div aria-live="polite">{loading && <p className="mt-6 rounded-xl bg-white p-6">Đang tải đơn hàng…</p>}{error && <p role="alert" className="mt-6 rounded-xl bg-red-50 p-6 text-red-800">{error}</p>}{!loading && !error && result?.data.length === 0 && <p className="mt-6 rounded-xl bg-white p-6">Không có đơn hàng phù hợp.</p>}</div>
    {!loading && !error && result && result.data.length > 0 && <><div className="mt-6 hidden overflow-hidden rounded-2xl bg-white shadow-sm lg:block"><table className="w-full text-left text-sm"><caption className="sr-only">Danh sách đơn hàng</caption><thead className="bg-slate-50"><tr>{["Mã đơn","Khách hàng","Điện thoại","Lịch lấy mẫu","Khu vực","Xét nghiệm","Tổng tiền","Trạng thái","Ngày tạo",""].map((h) => <th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{result.data.map((o) => <tr key={o.orderCode} className="border-t"><td className="p-3 font-semibold">{o.orderCode}</td><td className="p-3">{o.contactName}</td><td className="p-3">{o.maskedPhone}</td><td className="p-3">{o.appointment ? `${date(o.appointment.scheduledDate)} · ${o.appointment.timeSlot}` : "—"}</td><td className="p-3">{o.appointment ? `${o.appointment.district}, ${o.appointment.province}` : "—"}</td><td className="p-3">{o.itemCount}</td><td className="p-3">{formatMoney(o.totalAmount)}</td><td className="p-3">{o.statusLabel}</td><td className="p-3">{date(o.createdAt)}</td><td className="p-3"><Link className="font-semibold text-teal-700 underline" href={`/admin/orders/${o.orderCode}`}>Xem chi tiết</Link></td></tr>)}</tbody></table></div><div className="mt-6 grid gap-4 lg:hidden">{result.data.map((o) => <article key={o.orderCode} className="rounded-2xl bg-white p-5 shadow-sm"><div className="flex justify-between gap-3"><strong>{o.orderCode}</strong><span>{o.statusLabel}</span></div><p className="mt-2">{o.contactName} · {o.maskedPhone}</p><p>{o.appointment ? `${date(o.appointment.scheduledDate)} · ${o.appointment.timeSlot}` : "Chưa có lịch"}</p><p className="font-semibold">{formatMoney(o.totalAmount)}</p><Link className="mt-3 inline-block text-teal-700 underline" href={`/admin/orders/${o.orderCode}`}>Xem chi tiết</Link></article>)}</div><nav aria-label="Phân trang" className="mt-6 flex items-center justify-between"><button disabled={result.pagination.page <= 1} onClick={() => setParam("page", String(result.pagination.page - 1))} className="rounded border px-4 py-2 disabled:opacity-40">Trang trước</button><span>Trang {result.pagination.page}/{Math.max(1,result.pagination.totalPages)}</span><button disabled={result.pagination.page >= result.pagination.totalPages} onClick={() => setParam("page", String(result.pagination.page + 1))} className="rounded border px-4 py-2 disabled:opacity-40">Trang sau</button></nav></>}
  </>;
}
const date = (value: string) => new Intl.DateTimeFormat("vi-VN", { dateStyle: "short", timeStyle: "short" }).format(new Date(value));
