"use client";
/* eslint-disable react-hooks/set-state-in-effect */
import { FormEvent, useEffect, useState } from 'react';
import type { AdminOrderDetail } from '@/lib/admin-orders';
import { assignCollector, CollectorApiError, EligibleCollector, getEligibleCollectors, unassignCollector } from '@/lib/collectors';
export function CollectorAssignmentPanel({ order, onUpdated, onError }: { order: AdminOrderDetail; onUpdated: (order: AdminOrderDetail) => void; onError: (message: string) => void }) {
  const [open,setOpen]=useState(false),[mode,setMode]=useState<'assign'|'unassign'>('assign'),[eligible,setEligible]=useState<EligibleCollector[]>([]),[selected,setSelected]=useState(''),[search,setSearch]=useState(''),[reason,setReason]=useState(''),[loading,setLoading]=useState(false);
  useEffect(()=>{if(!open||mode!=='assign')return;let active=true;setLoading(true);getEligibleCollectors(order.orderCode,search).then(v=>{if(active)setEligible(v.data);}).catch(e=>active&&onError(e instanceof Error?e.message:'Không thể tải nhân viên.')).finally(()=>active&&setLoading(false));return()=>{active=false;};},[open,mode,order.orderCode,search,onError]);
  const submit=async(e:FormEvent)=>{e.preventDefault();if(loading)return;if(mode==='assign'&&!selected)return onError('Vui lòng chọn nhân viên.');if(mode==='unassign'&&reason.trim().length<3)return onError('Lý do phải có ít nhất 3 ký tự.');setLoading(true);try{const updated=mode==='assign'?await assignCollector(order.orderCode,order.version,selected):await unassignCollector(order.orderCode,order.version,reason.trim());onUpdated(updated);setOpen(false);setSelected('');setReason('');}catch(error){onError(error instanceof CollectorApiError?error.message:'Không thể cập nhật phân công.');}finally{setLoading(false);}};
  if(order.status!=='CONFIRMED'&&order.status!=='COLLECTOR_ASSIGNED')return null;
  return <section className="mb-5 rounded-2xl bg-white p-5 shadow-sm"><h2 className="text-xl font-bold">Nhân viên lấy mẫu</h2>{order.currentCollector?<div className="mt-2"><p>{order.currentCollector.employeeCode} · {order.currentCollector.fullName}</p><p>{order.currentCollector.maskedPhone} · {order.currentCollector.operationalStatus}</p><div className="mt-3 flex gap-2"><button className="rounded bg-teal-700 px-4 py-2 text-white" onClick={()=>{setMode('assign');setOpen(true);}}>Đổi nhân viên</button><button className="rounded border px-4 py-2" onClick={()=>{setMode('unassign');setOpen(true);}}>Gỡ phân công</button></div></div>:<button className="mt-3 rounded bg-teal-700 px-4 py-2 text-white" onClick={()=>{setMode('assign');setOpen(true);}}>Phân công nhân viên</button>}{open&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><form onSubmit={submit} role="dialog" aria-modal="true" aria-label={mode==='assign'?'Phân công nhân viên':'Gỡ phân công'} className="w-full max-w-lg rounded-2xl bg-white p-6"><h3 className="text-xl font-bold">{mode==='assign'?'Chọn nhân viên lấy mẫu':'Gỡ phân công'}</h3>{mode==='assign'?<><label className="mt-4 block">Tìm kiếm<input className="mt-1 w-full rounded border p-2" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="mt-3 max-h-64 overflow-auto">{loading?<p>Đang tải…</p>:eligible.length===0?<p>Không có nhân viên phù hợp.</p>:eligible.map(c=><label className="block border-b p-3" key={c.employeeCode}><input type="radio" name="collector" value={c.employeeCode} checked={selected===c.employeeCode} onChange={()=>setSelected(c.employeeCode)}/> <strong>{c.employeeCode}</strong> · {c.fullName} · {c.maskedPhone}</label>)}</div></>:<label className="mt-4 block">Lý do<textarea required maxLength={500} className="mt-1 w-full rounded border p-2" value={reason} onChange={e=>setReason(e.target.value)}/><small>{reason.length}/500 ký tự</small></label>}<div className="mt-4 flex justify-end gap-2"><button type="button" disabled={loading} onClick={()=>setOpen(false)} className="rounded border px-4 py-2">Đóng</button><button disabled={loading} className="rounded bg-teal-700 px-4 py-2 text-white">{loading?'Đang xử lý…':'Xác nhận'}</button></div></form></div>}</section>;
}
