import type { LabSpecimenDetail } from "@/lib/lab-portal";

export function LabSpecimenOverview({ specimen, showCustody = true }: { specimen: LabSpecimenDetail; showCustody?: boolean }) {
  return <div className="grid gap-5 lg:grid-cols-2">
    <section className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="text-sm text-slate-600">Mã bệnh phẩm</p><h2 className="font-mono text-xl font-bold">{specimen.specimenCode}</h2></div><span className="rounded-full bg-slate-100 px-3 py-1 text-sm font-bold">{specimen.status}</span></div><dl className="mt-4 grid grid-cols-[auto_1fr] gap-x-4 gap-y-2"><dt className="text-slate-600">Mã đơn</dt><dd>{specimen.orderCode}</dd><dt className="text-slate-600">Loại mẫu</dt><dd>{specimen.specimenType}</dd><dt className="text-slate-600">Ống chứa</dt><dd>{specimen.containerType}</dd><dt className="text-slate-600">Thể tích mục tiêu</dt><dd>{volume(specimen.targetVolumeMl)}</dd><dt className="text-slate-600">Thể tích đã lấy</dt><dd>{volume(specimen.collectedVolumeMl)}</dd><dt className="text-slate-600">Phiên bản</dt><dd>{specimen.version}</dd></dl></section>
    <section className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-bold">Đối chiếu người xét nghiệm</h2><p className="mt-3 font-semibold">{specimen.subject.displayName}</p><p>Ngày sinh: {specimen.subject.dateOfBirth}</p><p className="mt-3 text-sm text-slate-600">Chỉ sử dụng thông tin này cho bước đối chiếu tại phòng xét nghiệm.</p></section>
    <section className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-bold">Xét nghiệm liên kết</h2><ul className="mt-3 list-inside list-disc">{specimen.linkedTests.map((test) => <li key={test.testCode}>{test.testName} ({test.testCode})</li>)}</ul></section>
    <section className="rounded-2xl border bg-white p-5"><h2 className="text-xl font-bold">Mốc thời gian</h2><dl className="mt-3 grid grid-cols-[auto_1fr] gap-x-4 gap-y-2 text-sm"><dt>Đã lấy</dt><dd>{date(specimen.collectedAt)}</dd><dt>Vận chuyển</dt><dd>{date(specimen.inTransitAt)}</dd><dt>Tiếp nhận</dt><dd>{date(specimen.receivedAt)}</dd><dt>Chấp nhận</dt><dd>{date(specimen.acceptedAt)}</dd><dt>Từ chối</dt><dd>{date(specimen.rejectedAt)}</dd></dl>{specimen.rejectionReason && <p className="mt-3 rounded bg-red-50 p-3 text-red-800">Lý do từ chối: {specimen.rejectionReason}{specimen.recollectionRequired ? " · Cần lấy lại mẫu" : ""}</p>}</section>
    {showCustody && specimen.custodyTimeline && <section className="rounded-2xl border bg-white p-5 lg:col-span-2"><h2 className="text-xl font-bold">Chuỗi bàn giao</h2>{specimen.custodyTimeline.length === 0 ? <p className="mt-3 text-slate-600">Chưa có sự kiện bàn giao.</p> : <ol className="mt-4 space-y-4">{[...specimen.custodyTimeline].sort((a, b) => Date.parse(a.occurredAt) - Date.parse(b.occurredAt)).map((event, index) => <li key={`${event.occurredAt}-${event.eventType}-${index}`} className="border-l-4 border-teal-700 pl-4"><strong>{event.title}</strong><p className="text-sm">{event.actorType}{event.actorEmployeeCode ? ` · ${event.actorEmployeeCode}` : ""}</p><time className="text-sm text-slate-600">{date(event.occurredAt)}</time></li>)}</ol>}</section>}
  </div>;
}

const volume = (value: string | null) => value ? `${value} ml` : "Không ghi nhận";
const date = (value: string | null) => value ? new Intl.DateTimeFormat("vi-VN", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—";
