import type { AdminOrderDetail } from './admin-orders';
export type OperationalStatus = 'AVAILABLE' | 'OFF_DUTY' | 'INACTIVE';
export type ServiceArea = { province: string; district: string | null };
export type CollectorItem = { employeeCode: string; fullName: string; email: string; maskedPhone: string; operationalStatus: OperationalStatus; serviceAreas: ServiceArea[]; activeAssignmentCount: number; createdAt: string };
export type CollectorDetail = CollectorItem & { phone: string; staffStatus: 'ACTIVE' | 'INACTIVE'; updatedAt: string };
export type CollectorList = { data: CollectorItem[]; pagination: { page: number; limit: number; total: number; totalPages: number } };
export type EligibleCollector = { employeeCode: string; fullName: string; maskedPhone: string; serviceAreaMatch: true; isAvailable: true };
const apiUrl = process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:3001';
export class CollectorApiError extends Error { constructor(message: string, readonly status: number) { super(message); } }
async function request<T>(path: string, init?: RequestInit): Promise<T> { let response: Response; try { response = await fetch(`${apiUrl}${path}`, { ...init, credentials: 'include', cache: 'no-store', headers: { 'Content-Type': 'application/json', ...init?.headers }, signal: AbortSignal.timeout(10_000) }); } catch { throw new CollectorApiError('Không thể kết nối tới hệ thống.', 0); } if (!response.ok) { if (response.status === 401) throw new CollectorApiError('Phiên đăng nhập đã hết hạn.', 401); if (response.status === 403) throw new CollectorApiError('Bạn không có quyền thực hiện thao tác này.', 403); if (response.status === 404) throw new CollectorApiError('Không tìm thấy dữ liệu.', 404); if (response.status === 409) throw new CollectorApiError('Dữ liệu đã thay đổi hoặc thao tác không còn hợp lệ. Vui lòng tải lại.', 409); if (response.status === 400) throw new CollectorApiError('Thông tin gửi lên chưa hợp lệ.', 400); throw new CollectorApiError('Hệ thống chưa thể xử lý yêu cầu.', response.status); } return response.json() as Promise<T>; }
export const getCollectors = (query: string) => request<CollectorList>(`/admin/collectors${query ? `?${query}` : ''}`);
export const getCollector = (code: string) => request<CollectorDetail>(`/admin/collectors/${encodeURIComponent(code)}`);
export const updateCollectorStatus = (code: string, operationalStatus: OperationalStatus) => request<{ warning: string | null }>(`/admin/collectors/${encodeURIComponent(code)}/status`, { method: 'PATCH', body: JSON.stringify({ operationalStatus }) });
export const updateCollectorAreas = (code: string, serviceAreas: ServiceArea[]) => request<CollectorDetail>(`/admin/collectors/${encodeURIComponent(code)}/service-areas`, { method: 'PUT', body: JSON.stringify({ serviceAreas }) });
export const getEligibleCollectors = (orderCode: string, search = '') => request<{ data: EligibleCollector[] }>(`/admin/orders/${encodeURIComponent(orderCode)}/eligible-collectors${search ? `?search=${encodeURIComponent(search)}` : ''}`);
export const assignCollector = (orderCode: string, expectedVersion: number, collectorEmployeeCode: string) => request<AdminOrderDetail>(`/admin/orders/${encodeURIComponent(orderCode)}/assign-collector`, { method: 'PATCH', body: JSON.stringify({ expectedVersion, collectorEmployeeCode }) });
export const unassignCollector = (orderCode: string, expectedVersion: number, reason: string) => request<AdminOrderDetail>(`/admin/orders/${encodeURIComponent(orderCode)}/unassign-collector`, { method: 'PATCH', body: JSON.stringify({ expectedVersion, reason }) });
