import { afterEach,describe,expect,it,vi } from 'vitest';
import { collectSpecimens,CollectorPortalError,getCollectorOrders,reportFailure } from '@/lib/collector-portal';
const json=(value:unknown,status=200)=>new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json'}});
afterEach(()=>vi.unstubAllGlobals());
describe('collector portal API client',()=>{
  it('loads only non-sensitive list contract with credentials and no cache',async()=>{const fetchMock=vi.fn().mockResolvedValue(json({data:[],pagination:{page:1,limit:20,total:0,totalPages:0}}));vi.stubGlobal('fetch',fetchMock);await getCollectorOrders('date=2026-08-05&status=COLLECTOR_ASSIGNED');expect(fetchMock.mock.calls[0]?.[0]).not.toContain('phone');expect(fetchMock.mock.calls[0]?.[1]).toMatchObject({credentials:'include',cache:'no-store'});});
  it('sends scanned specimens and confirmations without raw subject identifiers',async()=>{const fetchMock=vi.fn().mockResolvedValue(json({}));vi.stubGlobal('fetch',fetchMock);await collectSpecimens('HL-SYNTHETIC',{expectedVersion:4,operationId:'00000000-0000-4000-8000-000000000001',identityConfirmation:{fullNameConfirmed:true,dateOfBirthConfirmed:true},consentConfirmed:true,specimens:[{barcodeValue:'opaque-synthetic-barcode',collectedVolumeMl:'3.5'}]});const body=String(fetchMock.mock.calls[0]?.[1]?.body);expect(JSON.parse(body)).toMatchObject({expectedVersion:4,identityConfirmation:{fullNameConfirmed:true,dateOfBirthConfirmed:true},consentConfirmed:true});expect(body).not.toContain('fullName":"');expect(body).not.toContain('dateOfBirth":"');expect(fetchMock.mock.calls[0]?.[0]).toContain('/collect-specimens');});
  it('does not retry stale failure mutations',async()=>{const fetchMock=vi.fn().mockResolvedValue(json({message:'stale'},409));vi.stubGlobal('fetch',fetchMock);await expect(reportFailure('HL-SYNTHETIC',2,'OTHER','Synthetic operational note')).rejects.toBeInstanceOf(CollectorPortalError);expect(fetchMock).toHaveBeenCalledTimes(1);});
});
